### PR TITLE
[scrapers] scrape Le Lab Quantique.

### PR DESCRIPTION
**Pull request by cimandef**
## Objectif
- Scrape Le Lab Quantique website for quantum news.

### CODE REVIEW

**Comment by stubbi** [comment]
@Angel-Dijoux thanks for the request! I didn't know there was a news section. Will it work yet?

**Comment by cimandef** [comment]
> I didn't know there was a news section

Yes since 2020 ! We have around of 35 articles in Le Lab Quantique website.

> Will it work yet

Technically yes, we should write a article before or after each LLQ events, but right now isn't directly accessible because LLQ website is in maintenance mode.

**Comment by cimandef** [comment]
I'll see to change the way I implement graphql in wordpress, maybe my queries can be changed, we will wait before merge !

**Comment by cimandef** [comment]
@stubbi  You can merge it, if is okay for you!

**Review by stubbi — APPROVED** [review]

**Comment by stubbi** [comment]
@Angel-Dijoux cool! done

**Pull request merged**
